#######################
# 开发环境的profiles文件#
#######################

#服务器端口设置
server:
  #服务端口号
  port: 8010


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

#SL4fj的配置
logging:
  level:
    cn.ykd.store: trace



# 当前项目中的自定义配置
ykd:
  # 与JWT相关的配置
  jwt:
    # 生成和解析JWT时使用的secret-key
    secret-key: asdghftrhr,ertrtrgfsfgf.
    # JWT的有效时长，以分钟为单位
    duration-in-minute: 14400